### ISSUE TITLE
cant run TxtSyle

### ISSUE THREAD

**Issue by something-wrong** [armandino/TxtStyle#2]
heare the output from cli

ifconfig | txts -n ifconfig
Traceback (most recent call last):
  File "/usr/local/bin/txts", line 33, in <module>
    sys.exit(load_entry_point('TxtStyle==1.1.1', 'console_scripts', 'txts')())
  File "/usr/local/lib/python3.6/dist-packages/TxtStyle-1.1.1-py3.6.egg/txtstyle/txts.py", line 163, in main
  File "/usr/local/lib/python3.6/dist-packages/TxtStyle-1.1.1-py3.6.egg/txtstyle/txts.py", line 50, in transform
  File "/usr/local/lib/python3.6/dist-packages/TxtStyle-1.1.1-py3.6.egg/txtstyle/txts.py", line 77, in _transform_pipe
  File "/usr/local/lib/python3.6/dist-packages/TxtStyle-1.1.1-py3.6.egg/txtstyle/txts.py", line 85, in _style
  File "/usr/local/lib/python3.6/dist-packages/TxtStyle-1.1.1-py3.6.egg/txtstyle/transformer.py", line 62, in style
  File "/usr/local/lib/python3.6/dist-packages/TxtStyle-1.1.1-py3.6.egg/txtstyle/linestyleprocessor.py", line 21, in get_style_map
  File "/usr/local/lib/python3.6/dist-packages/TxtStyle-1.1.1-py3.6.egg/txtstyle/linestyleprocessor.py", line 59, in find_regions
AttributeError: module 're' has no attribute 'Pattern'

**Comment by armandino** [comment]
Looks like it's not working with Python 3.6. I need to update the README.

Can you try with Python 3.7+?
